
package GUI;
import courier.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ParcelManagementFrame extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParcelManagementFrame.class.getName());
   
   // Add this line to initialize the manager
    private ParcelManager parcelManager = new ParcelManager();

    /**
     * Creates new form ParcelManagementFrame
     */
    public ParcelManagementFrame() {
        initComponents();
        // Centers the window on the screen
        setLocationRelativeTo(null);
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Express" }));
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FieldReceiver = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FieldWeight = new javax.swing.JTextField();
        btnBackD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FieldTrackid = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FieldSender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        FieldSurcharge = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FieldReceiver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldReceiver.addActionListener(this::FieldReceiverActionPerformed);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete Parcel");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Weight (kg):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sender:");

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setText("View Receipt");
        btnView.addActionListener(this::btnViewActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tracking ID", "Type", "Sender", "Receiver", "Weight", "Status", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        FieldWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldWeight.addActionListener(this::FieldWeightActionPerformed);

        btnBackD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackD.setText("Back to Dashboard");
        btnBackD.addActionListener(this::btnBackDActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Receiver:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Type:");

        FieldTrackid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldTrackid.addActionListener(this::FieldTrackidActionPerformed);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sdandard" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add Parcel");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Priority Surcharge:");

        FieldSender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldSender.addActionListener(this::FieldSenderActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tracking ID:  ");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update Status");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        FieldSurcharge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldSurcharge.addActionListener(this::FieldSurchargeActionPerformed);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Parcel Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBackD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldTrackid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldSender)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldReceiver)
                            .addComponent(FieldSurcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(FieldTrackid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldSender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(FieldSurcharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnView)
                    .addComponent(btnBackD))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldReceiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldReceiverActionPerformed
        // Reciver
    }//GEN-LAST:event_FieldReceiverActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // btn delete
        String id = FieldTrackid.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a parcel to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Parcel " + id + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (parcelManager.deleteParcel(id)) {
                refreshTable();
                clearFields();
                JOptionPane.showMessageDialog(this, "Parcel Deleted!");
            } else {
                JOptionPane.showMessageDialog(this, "Parcel not found!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        //btn view recipt
        String id = FieldTrackid.getText().trim();
        Parcel p = parcelManager.findByTrackingId(id);

        if (p == null) {
            JOptionPane.showMessageDialog(this, "Please select a valid parcel from the table.");
            return;
        }

        StringBuilder receipt = new StringBuilder();
        receipt.append("=== COURIER RECEIPT ===\n");
        receipt.append("Tracking ID : ").append(p.getTrackingId()).append("\n");
        receipt.append("Type        : ").append(p.getParcelType()).append("\n");
        receipt.append("Sender      : ").append(p.getSender()).append("\n");
        receipt.append("Receiver    : ").append(p.getReceiver()).append("\n");
        receipt.append("Weight      : ").append(p.getWeight()).append(" kg\n");
        receipt.append("Status      : ").append(p.getStatus()).append("\n");
        receipt.append("----------------------------\n");
        receipt.append(String.format("TOTAL PRICE : Rs. %.2f\n", p.calculatePrice()));
        receipt.append("=======================");

        JOptionPane.showMessageDialog(this, receipt.toString(), "Receipt", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewActionPerformed

    private void FieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldWeightActionPerformed
        // Weight
    }//GEN-LAST:event_FieldWeightActionPerformed

    private void btnBackDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDActionPerformed
        // back to dashboard
        /*    new LoginFrame().setVisible(true);
        this.dispose(); */

        DashboardFrame mainMenu = new DashboardFrame();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackDActionPerformed

    private void FieldTrackidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTrackidActionPerformed
        //tracking id
    }//GEN-LAST:event_FieldTrackidActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // combo box - sand and express
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // btn add
        try{
            String id = FieldTrackid.getText().trim();
            String sender = FieldSender.getText().trim();
            String receiver = FieldReceiver.getText().trim();
            String type = jComboBox1.getSelectedItem().toString();

            //check if empty
            if(id.isEmpty() || sender.isEmpty() || receiver.isEmpty() || FieldWeight.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in all required fields!");
                return;
            }

            double weight = Double.parseDouble(FieldWeight.getText().trim());
            Parcel p;

            if (type.equals("Express")){
                double surcharge = FieldSurcharge.getText().trim().isEmpty() ? 0.0 : Double.parseDouble(FieldSurcharge.getText().trim());
                p = new ExpressParcel(id, sender, receiver, weight, "Pending", surcharge);
            }else {
                p = new StandardParcel(id, sender, receiver, weight, "Pending");
            }

            if(parcelManager.addParcel(p)){
                JOptionPane.showMessageDialog(this, "Parcel Added Successfully!");
                refreshTable();
                clearFields();
            } else{
                JOptionPane.showMessageDialog(this, "A Parcel with this Tracking ID already exists!");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Weight and Surcharge must be valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void FieldSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldSenderActionPerformed
        //Sender
    }//GEN-LAST:event_FieldSenderActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //btn update
        String id = FieldTrackid.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select or type a Tracking ID first.");
            return;
        }

        String[] options = {"Pending", "In Transit", "Delivered"};
        String newStatus = (String) JOptionPane.showInputDialog(this, "Select New Status:",
            "Update Status", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (newStatus != null) {
            if (parcelManager.updateStatus(id, newStatus)) {
                refreshTable();
                JOptionPane.showMessageDialog(this, "Status Updated!");
            } else {
                JOptionPane.showMessageDialog(this, "Parcel not found!");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void FieldSurchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldSurchargeActionPerformed
        // surcharge
    }//GEN-LAST:event_FieldSurchargeActionPerformed

    //new table methods
    private void refreshTable() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        
        tableModel.setRowCount(0);
        for (Parcel p : parcelManager.getAllParcels()) {
            tableModel.addRow(new Object[]{
                p.getTrackingId(), 
                p.getParcelType(), 
                p.getSender(), 
                p.getReceiver(), 
                p.getWeight(), //Double
                p.getStatus(), 
                p.calculatePrice() // String.formatDouble .
            });
        }
    }

    // Text Boxes හිස් කරන Method එක
    private void clearFields() {
        FieldTrackid.setText("");
        FieldSender.setText("");
        FieldReceiver.setText("");
        FieldWeight.setText("");
        FieldSurcharge.setText("");
        jComboBox1.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ParcelManagementFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldReceiver;
    private javax.swing.JTextField FieldSender;
    private javax.swing.JTextField FieldSurcharge;
    private javax.swing.JTextField FieldTrackid;
    private javax.swing.JTextField FieldWeight;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackD;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
